/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "JwtSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostgresDb": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostgresHost": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostgresPassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PostgresUser": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}

import "sst"
export {}